parser: babel-eslint
extends:
  - airbnb
  - prettier
  - plugin:prettier/recommended
  - prettier/babel
  - prettier/react
  - '@react-native-community'
plugins:
  - prettier
  - react
  - jsx-a11y
  - import
rules:
  prettier/prettier: error
  react/jsx-filename-extension: off
  react/prop-types:
    - error
    - ignore: [navigation]
  no-console: error
